"""
This file is used to store useful constants related to the Recorder class
"""

NAME = "name"
INDEX = "index"
METRICS = "metrics"
TRAIN_METRICS = "train_metrics"
TEST_METRICS = "test_metrics"
HYPERPARAMETERS = "hyperparameters"
HYPERPARAMETER_IMPORTANCE = "hyperparameter_importance"
PREDICTION = "prediction"
TRAIN_RESULTS = "train_results"
TEST_RESULTS = "test_results"
RESULTS = "results"
INFO = "info"
VALUES = "values"
MEAN = "mean"
STD = "std"
ACCURACY = "accuracy"
DATA_INFO = "data_info"
COEFFICIENT = "coefficient"
TARGET = "target"
