"""
Author : Nicolas Raymond

This file is used to store helpful constants for table extracting

"""
from numpy import nan

# SEED VALUE FOR HOLDOUT SETS
SEED = 110796

# DATA CLEANING THRESHOLDS
COLUMN_REMOVAL_THRESHOLD = 0.20
ROW_REMOVAL_THRESHOLD = 0.20
OUTLIER_ALPHA = 1.5


# TABLE NAMES
GEN_1 = "General_1_Demographic Questionnaire"
GEN_2 = "General_2_CRF Hematology-Oncology"
CARDIO_0 = "Cardio_0_Évaluation à l'Effort (EE)"
CARDIO_3 = "Cardio_3_Questionnaire d'Activité Physique (QAP)"
CARDIO_4 = "Cardio_4_Test de Marche de 6 Minutes (TDM6)"
VO2_ID_TABLE = "VO2_ID"
INVALID_ID_TABLE = "INVALID_ID"
DEX_DOX_TABLE = "DEX_DOX"
PETALE_PANDORA = "PETALE_PANDORA"
SNPS_RARE = "SNPS_RARE"
SNPS_COMMON = "SNPS_COMMON"
SIGNIFICANT_COMMON_SNPS_ID = "SIGNIFICANT_COMMON_SNPS_ID"
SIGNIFICANT_RARE_SNPS_ID = "SIGNIFICANT_RARE_SNPS_ID"
GENERALS = "GENERALS"
TOP5_SNPS_ID = "TOP5_SNPS_ID"
TOP12_SNPS_ID = "TOP12_SNPS_ID"
GENES_5 = "GENES_5"
GENES_12 = "GENES_12"
SIXMWT = "6MWT"
BASE_FEATURES_AND_COMPLICATIONS = "BASELINE_FEATURES_AND_COMPLICATIONS"
BASE_FEATURES_AND_COMPLICATIONS_PLUS_FITNESS = "BASE_FEATURES_AND_COMPLICATIONS_+_FITNESS"
LEARNING_0 = "L0_WARMUP"
LEARNING_0_HOLDOUT = "L0_WARMUP_HOLDOUT"
LEARNING_1 = "L1_BASELINES_CARDIOMETABOLIC"
LEARNING_1_HOLDOUT = "L1_BASELINES_CARDIOMETABOLIC_HOLDOUT"
LEARNING_1_1 = "L1_BASELINES_&_GENES_CARDIOMETABOLIC"
LEARNING_1_1_HOLDOUT = "L1_BASELINES_&_GENES_CARDIOMETABOLIC_HOLDOUT"
RAW = "RAW"


# TABLE KEYS AND FILTERS
PARTICIPANT, TAG, DATE = "Participant", "Tag", "Date"
PHASE = "Phase 1"
INNER = "inner"
PKEY = [PARTICIPANT, TAG]

# DATA TYPE
DATE_TYPE = "date"
NUMERIC_TYPE = "numeric"
CATEGORICAL_TYPE = "text"

# GENERAL 1 COLUMNS
SEX = "34500 Sex"
DATE_OF_BIRTH = "34501 Date of birth (survivor)"
HEIGHT = "34502 Height"
WEIGHT = "34503 Weight"
SMOKING = "34604 Is currently smoking?"
BIRTH_AGE = "34592 Gestational age at birth"
BIRTH_WEIGHT = "34593 Weight at birth"
SEX_CATEGORIES = {0: "Women", 1: "Men"}
BIRTH_AGE_CATEGORIES = {1: "<37w", 2: ">=37w", 9: nan}
BIRTH_WEIGHT_CATEGORIES = {1: "<2500g", 2: ">=2500g", 9: nan}

# GENERAL 2 COLUMNS
DATE_OF_DIAGNOSIS = "34471 Date of diagnosis"
AGE_AT_DIAGNOSIS = "34472 Age at diagnosis"
DATE_OF_TREATMENT_END = "34474 Date of treatment end"
RADIOTHERAPY = "34479 Radiotherapy?"
RADIOTHERAPY_DOSE = "34480 Radiotherapy dose"
METABOLIC_COMPLICATIONS = "34482 Metabolic complications?"
BONE_COMPLICATIONS = "34483 Skeletal/bone complications?"
CARDIAC_COMPLICATIONS = "34484 Cardiac complications?"
NEUROCOGNITIVE_COMPLICATIONS = "34485 Neurocognitive complications?"

# CARDIO 0 COLUMNS
VO2_MAX = "35006 EE_VO2_max"
VO2_MAX_PRED = "35008 EE_VO2_max_pred"
VO2R_MAX = "35009 EE_VO2r_max"
TAS_REST = "35020 EE_TAS_rest"
TAD_REST = "35021 EE_TAD_rest"

# CARDIO 3 COLUMNS
MVLPA = "35116 QAPL8"

# CARDIO 4 COLUMNS
TDM6_DIST = "35142 TDM6_Distance_2"
TDM6_HR_REST = "35143 TDM6_HR_rest_2"
TDM6_HR_END = "35149 TDM6_HR_6_2"
TDM6_TAS_END = "35152 TDM6_TAS_effort_2"
TDM6_TAD_END = "35153 TDM6_TAD_effort_2"

# DEX_DOX COLUMNS
DEX = 'DEX (mg/m2)'
DOX = 'DOX (mg/m2)'

# SIGNIFICANT SNPs COLUMNS
GENES = "Genes"
SNPS_ID = "SNPs ID"
CHROM = "CHROM"
SNPS_POSITION = "POS"
REF = "REF"
ALT = "ALT"
GENE_REF_GEN = "Generefgene"


# TOP 5-12 SNPS COLUMNS
SNPS_TYPE = "TYPE"
SIGNIFICANT_CHROM_POS = ['1_115231254', '1_66036441', '17_4856580', '2_179498042',
                         '3_122003769', '4_2916762', '7_45932669', '6_110768128']

# PETALE PANDORA COLUMNS
REF_NAME = "Reference name"

# NEW COLUMNS NAMES
TSEOT = "Time since end of treatment"
DT = "Duration of treatment"
AGE = "Age"
FITNESS = "Fitness"
FITNESS_COMPLICATIONS = "Fitness complications?"
CARDIOMETABOLIC_COMPLICATIONS = "Cardiometabolic complications?"

# TYPE DICT
TYPES = {PARTICIPANT: CATEGORICAL_TYPE,
         TAG: CATEGORICAL_TYPE,
         DATE: DATE_TYPE,
         SEX: CATEGORICAL_TYPE,
         DATE_OF_BIRTH: DATE_TYPE,
         HEIGHT: NUMERIC_TYPE,
         WEIGHT: NUMERIC_TYPE,
         SMOKING: CATEGORICAL_TYPE,
         DATE_OF_DIAGNOSIS: DATE_TYPE,
         AGE_AT_DIAGNOSIS: NUMERIC_TYPE,
         DATE_OF_TREATMENT_END: DATE_TYPE,
         RADIOTHERAPY: CATEGORICAL_TYPE,
         RADIOTHERAPY_DOSE: CATEGORICAL_TYPE,
         VO2_MAX: NUMERIC_TYPE,
         VO2_MAX_PRED: NUMERIC_TYPE,
         VO2R_MAX: NUMERIC_TYPE,
         TAS_REST: NUMERIC_TYPE,
         TAD_REST: NUMERIC_TYPE,
         MVLPA: NUMERIC_TYPE,
         TDM6_DIST: NUMERIC_TYPE,
         TDM6_HR_REST: NUMERIC_TYPE,
         TDM6_HR_END: NUMERIC_TYPE,
         TDM6_TAS_END: NUMERIC_TYPE,
         TDM6_TAD_END: NUMERIC_TYPE,
         DEX: CATEGORICAL_TYPE,
         DOX: NUMERIC_TYPE,
         TSEOT: NUMERIC_TYPE,
         DT: NUMERIC_TYPE,
         AGE: NUMERIC_TYPE,
         FITNESS_COMPLICATIONS: CATEGORICAL_TYPE,
         BIRTH_AGE: CATEGORICAL_TYPE,
         BIRTH_WEIGHT: CATEGORICAL_TYPE,
         METABOLIC_COMPLICATIONS: CATEGORICAL_TYPE,
         BONE_COMPLICATIONS: CATEGORICAL_TYPE,
         CARDIAC_COMPLICATIONS: CATEGORICAL_TYPE,
         NEUROCOGNITIVE_COMPLICATIONS: CATEGORICAL_TYPE,
         CARDIOMETABOLIC_COMPLICATIONS: CATEGORICAL_TYPE,
         GENES: CATEGORICAL_TYPE,
         SNPS_ID: CATEGORICAL_TYPE,
         SNPS_TYPE: CATEGORICAL_TYPE,
         CHROM: NUMERIC_TYPE,
         SNPS_POSITION: NUMERIC_TYPE,
         REF_NAME: CATEGORICAL_TYPE,
         }

# CLEANING RECORDS FOLDER
CLEANING_RECORDS = "CleaningRecords"

